name: ktea
description: An interior design mobile app created in GetX state management.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animate_do: ^3.1.2
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_fadein: ^2.0.0
  flutter_svg: ^2.0.7
  get: ^4.6.6
  page_transition: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/user.svg
    - assets/icons/bag.svg
    - assets/icons/arrow_long_left.svg
    - assets/icons/arrow_forward.png
    - assets/icons/check.svg
    - assets/icons/home.svg
    - assets/icons/menu.svg
    - assets/icons/ripple.gif
    - assets/icons/scan.svg
    - assets/icons/search.svg
    - assets/icons/spinner.gif
    - assets/icons/app_icon_black.png
    - assets/icons/home_black.svg
    - assets/icons/home.png
    - assets/icons/cart_20.png
    - assets/icons/app_icon_black_25.png
    - assets/icons/app_icon_white_25.png
    - assets/icons/app_icon_white.png
    - assets/icons/notification_bell_23.png
    - assets/icons/camera_25.png
    - assets/icons/camera_15.png
    - assets/icons/chat_white_20.png
    - assets/icons/chat_20.png
    - assets/icons/search_23.png
    - assets/icons/save_20.png
    - assets/icons/camera_icon.svg
    - assets/icons/copyright_20.png
    - assets/icons/user_20.png
    - assets/icons/help_20.png
    - assets/icons/logout_20.png
    - assets/icons/notification_20.png
    - assets/icons/hot_sale_20.png
    - assets/icons/settings_20.png
    - assets/icons/location_10.png
    - assets/icons/categories_20.png
    - assets/icons/right-down.png
    - assets/icons/categories_25.png
    - assets/images/splash/splash.jpg
    - assets/images/carousel/1.jpg
    - assets/images/carousel/2.jpg
    - assets/images/carousel/3.jpg
    - assets/images/carousel/4.jpg
    - assets/images/drawer/1.jpg
    - assets/images/drawer/model.jpg
    - assets/category_menu/cabinet_bkg.jpg
    - assets/category_menu/home_deco_bkg.jpg
    - assets/category_menu/light_bkg.jpg
    - assets/category_menu/sofa_bkg.jpg
    - assets/category_menu/table_bkg.jpg
    - assets/category_menu/cabinet.png
    - assets/category_menu/home_deco_250.png
    - assets/category_menu/cabinet_350.png
    - assets/category_menu/light_180.png
    - assets/category_menu/sofa_200.png
    - assets/category_menu/table_350.png
    - assets/products/home_decoration/1_150.jpg
    - assets/products/home_decoration/2_160.jpg
    - assets/products/home_decoration/3_150.jpg
    - assets/products/home_decoration/4_150.jpg
    - assets/products/light/1.jpg
    - assets/products/light/2.jpg
    - assets/products/light/3.jpg
    - assets/products/light/myntra.jpg
    - assets/products/sofa/1_150.jpg
    - assets/products/sofa/2_150.jpg
    - assets/products/sofa/3_150.jpg
    - assets/products/sofa/4_150.jpg
    - assets/products/table/1_150.jpg
    - assets/products/table/2_150.jpg
    - assets/products/table/3_150.jpg
    - assets/products/table/4_150.jpg
    - assets/products/cabinet/9tier_shoe_rack.jpg
    - assets/products/cabinet/clothes_hanger.jpg
    - assets/products/cabinet/triangle_coat_rack.jpg
    - assets/products/cabinet/handy_cabinet.jpg

    # Splash Screen Images.
    - assets/images/splash/1.jpg
    - assets/images/splash/2.jpg
    - assets/images/splash/3.jpg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
